services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: WebCrawler-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "WebCrawller123!"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - crawler-network
    restart: always

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq_manager
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - crawler-network
    restart: always

volumes:
  sqlserver-data:
  rabbitmq_data:

networks:
  crawler-network:
    driver: bridge